language: python

python:
  - 3.6

services:
  - docker

addons:
  apt:
    packages:
    - postgresql-client

env:
  global:
  - PGPORT=5432
  - PGHOST=127.0.0.1
  - PGDATABASE=mobilitydb
  - PGUSER=docker
  - PGPASSWORD=docker

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - docker pull codewit/mobilitydb
  - docker run -d -p 5432:5432 codewit/mobilitydb

install:
  - pip install ".[test]" . # install package + test dependencies
  - while ! psql -l; do ps afxhu | cat; echo "Waiting for MobilityDB to be ready..."; sleep 10; done
  - psql -l

script: pytest # run tests

after_success:
  - codecov # submit coverage

